### PR TITLE
fix: Use the browser builtin URL class if it exists

### PR DESCRIPTION
**Pull request by DecentM**
This PR enables this package to use the builtin URL api if it's running in a browser.  
I've also added some configuration to XO so that it now expects the Node + browser context.  

I haven't managed to add tests for the added if statement, because it checks for the existance of the global `window` object, which doesn't exist under Node. If you have any recommendation on how this can be tested in a future proof way, Id be happy to attempt to implement it!

### CODE REVIEW

**Comment by eight04** [comment]
Isn't it impossible to run CommonJS module in browsers? Are you using a build system? BTW, when we generate the [browserified dist](https://unpkg.com/usercss-meta@0.5.0/dist/usercss-meta.min.js), we shim the `url` module with something like this:
https://github.com/StylishThemes/parse-usercss/blob/c733681dc4dfb33518c414d761ca13c94ca865c1/rollup.config.js#L8

**Comment by DecentM** [comment]
I'm using Webpack which just takes the `main` entry from the package.json and bundles it into its tree.  
This method uses the source code and not the dist version. Do you want to propose an alternative solution?

**Comment by eight04** [comment]
I'm not familiar with Webpack, but I'm pretty sure that in rollup/browserify, unless they can statically evaluate `isBrowser` and `window.URL` expression to truthy, the `url` module won't be tree-shaken i.e. the `url` module is still bundled. Does webpack work differently?

Another approach is to use [`browser` field](https://github.com/defunctzombie/package-browser-field-spec) to map `url` module to a shim file.

**Comment by DecentM** [comment]
To my knowledge, tree-shaking just removes imports that will never be used. It's up to the minifier to then remove the module. This means you're correct on the module not being removed.  
Maybe it would be a good idea to have a separate build for browsers and Node with the `browser` field you mentioned.

**Pull request closed without merging**
